# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b72d1c4394adccb6924b7a606d458e48ddf872dfe6599822236d4471bda3bf39cfc86a7e0c3b6c49f41d663eec5031497b29999155ed8cfb8ab38379fa23609b

test:
  secret_key_base: a6252913142a34d5540b83115b7f86b24b60d2dfcc05aa27c87847626ad8d9df217f8d839f008458c2b67663389cc60966d5dde935eb39625c28a75de1b1e1db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
